version: '3.8'

services:
  web:
    build: .
    container_name: correcoes_vorazes_form
    ports:
      - "6050:80"
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    restart: unless-stopped